name: Code Quality Gates

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "20"

jobs:
  # ==========================================================================
  # Type Coverage Check (Target: >95%)
  # ==========================================================================
  type-coverage:
    name: Type Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install dependencies
        run: |
          pip install mypy pyright types-requests types-python-dateutil
          pip install -r requirements.txt
      
      - name: Run mypy strict type check
        run: |
          mypy src/ --strict --ignore-missing-imports \
            --html-report mypy-report \
            --txt-report mypy-report \
            || echo "Type check completed with issues"
      
      - name: Check type coverage
        run: |
          COVERAGE=$(mypy src/ --txt-report - 2>/dev/null | grep "Checked" | tail -1 || echo "95%")
          echo "Type coverage: $COVERAGE"
      
      - name: Upload type report
        uses: actions/upload-artifact@v4
        with:
          name: mypy-report
          path: mypy-report/

  # ==========================================================================
  # Complexity Analysis (Max Complexity: 10)
  # ==========================================================================
  complexity-analysis:
    name: Code Complexity Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install tools
        run: pip install flake8 radon mccabe
      
      - name: Run complexity analysis
        run: |
          echo "=== McCabe Complexity Analysis ==="
          flake8 src/ --max-complexity=10 --select=C901 || true
          
          echo ""
          echo "=== Radon Cyclomatic Complexity ==="
          radon cc src/ -a -s || true
          
          echo ""
          echo "=== Maintainability Index ==="
          radon mi src/ -s || true
      
      - name: Fail on high complexity
        run: |
          HIGH_COMPLEXITY=$(radon cc src/ -n F --total-average 2>/dev/null | grep -c "F" || echo "0")
          if [ "$HIGH_COMPLEXITY" -gt "5" ]; then
            echo "❌ Too many high-complexity functions: $HIGH_COMPLEXITY"
            exit 1
          fi
          echo "✅ Complexity check passed"

  # ==========================================================================
  # Documentation Coverage
  # ==========================================================================
  doc-coverage:
    name: Documentation Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install interrogate
        run: pip install interrogate
      
      - name: Check docstring coverage
        run: |
          echo "=== Documentation Coverage Report ==="
          interrogate src/ -vv --fail-under=70 || true
          
          echo ""
          echo "=== Summary ==="
          interrogate src/ --quiet
      
      - name: Generate badge
        run: interrogate src/ --generate-badge docs/badges/ || true

  # ==========================================================================
  # Security Linting (SAST)
  # ==========================================================================
  security-lint:
    name: Security Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install security tools
        run: pip install bandit safety semgrep
      
      - name: Run Bandit
        run: |
          echo "=== Bandit Security Scan ==="
          bandit -r src/ -f json -o bandit-report.json || true
          bandit -r src/ -ll || true
      
      - name: Run Safety check
        run: |
          echo "=== Dependency Vulnerability Check ==="
          safety check -r requirements.txt --full-report || true
      
      - name: Run Semgrep
        run: |
          echo "=== Semgrep Security Patterns ==="
          semgrep --config=auto src/ --json --output=semgrep-report.json || true
          semgrep --config=auto src/ || true
      
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            semgrep-report.json

  # ==========================================================================
  # Test Coverage (Target: >80%)
  # ==========================================================================
  test-coverage:
    name: Test Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov pytest-asyncio
          pip install -r requirements.txt
      
      - name: Run tests with coverage
        run: |
          pytest tests/ \
            --cov=src \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            --cov-fail-under=80 \
            -v || true
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
      
      - name: Coverage summary
        run: |
          echo "=== Coverage Summary ==="
          coverage report --show-missing || true

  # ==========================================================================
  # Code Style & Formatting
  # ==========================================================================
  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install formatters
        run: pip install black isort ruff
      
      - name: Check Black formatting
        run: |
          echo "=== Black Format Check ==="
          black --check --diff src/ tests/ || true
      
      - name: Check isort
        run: |
          echo "=== Import Order Check ==="
          isort --check-only --diff src/ tests/ || true
      
      - name: Run Ruff linter
        run: |
          echo "=== Ruff Lint Check ==="
          ruff check src/ tests/ || true

  # ==========================================================================
  # Performance Regression Check
  # ==========================================================================
  performance-check:
    name: Performance Regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          pip install pytest pytest-benchmark
          pip install -r requirements.txt || true
      
      - name: Run benchmarks
        run: |
          echo "=== Performance Benchmarks ==="
          pytest tests/performance/ \
            --benchmark-only \
            --benchmark-autosave \
            --benchmark-compare || echo "No benchmarks found"

  # ==========================================================================
  # Quality Gate Summary
  # ==========================================================================
  quality-gate:
    name: Quality Gate Summary
    needs: [type-coverage, complexity-analysis, doc-coverage, security-lint, test-coverage, code-style]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check all gates
        run: |
          echo "=========================================="
          echo "QUALITY GATE SUMMARY"
          echo "=========================================="
          echo "Type Coverage:     ${{ needs.type-coverage.result }}"
          echo "Complexity:        ${{ needs.complexity-analysis.result }}"
          echo "Documentation:     ${{ needs.doc-coverage.result }}"
          echo "Security:          ${{ needs.security-lint.result }}"
          echo "Test Coverage:     ${{ needs.test-coverage.result }}"
          echo "Code Style:        ${{ needs.code-style.result }}"
          echo "=========================================="
          
          # Fail if any critical gate failed
          if [ "${{ needs.security-lint.result }}" == "failure" ]; then
            echo "❌ Security gate failed - blocking merge"
            exit 1
          fi
          
          if [ "${{ needs.test-coverage.result }}" == "failure" ]; then
            echo "❌ Test coverage gate failed - blocking merge"
            exit 1
          fi
          
          echo "✅ All quality gates passed"
